using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Global.Domain;
using NSLDS.Domain;

namespace NSLDS.API.Tests.Common.TestLookupData
{
	public static class FakeFahLookups
	{
		public static IQueryable<FahAlert> GetTestFahAlertLookups()
		{
			List<FahAlert> fa = new List<FahAlert>()
			{
				new FahAlert() { Id =  "1", Description = "NULL", Name = "Warnings Errors & Alerts" },
				new FahAlert() { Id =  "10", Description = "NULL", Name = "Undergraduate Loans Remaining Eligibility - Combined Dependent" },
				new FahAlert() { Id =  "11", Description = "NULL", Name = "Undergraduate Loans Remaining Eligibility - Combined Independent" },
				new FahAlert() { Id =  "12", Description = "NULL", Name = "Graduate Loans Remaining Eligibility - Combined" },
				new FahAlert() { Id =  "13", Description = "NULL", Name = "Graduate Subsidized Loan Limit Flag indicating the condition of the Aggregate Total for subsidized loan limit(Loan types include: D0 D1 D6  subsidized SF  and calculated share of consolidation loan considered to be subsidized.) for a borrower with cumulative balances having undergraduate and graduate loans" },
				new FahAlert() { Id = "14", Description = "NULL", Name = "Subsidized Usage Limit Applies (SULA) indicator on loan" },
				new FahAlert() { Id = "15", Description = "NULL", Name = "TEACH Grant Converted to Loan" },
				new FahAlert() { Id = "16", Description = "NULL", Name = "Pell LEU Remaining Eligibility" },
				new FahAlert() { Id = "17", Description = "NULL", Name = "Annual Pell for AY 1" },
				new FahAlert() { Id = "2", Description = "NULL", Name = "Fraud Flag" },
				new FahAlert() { Id = "3", Description = "NULL", Name = "Active Bankruptcy Flag" },
				new FahAlert() { Id = "4", Description = "NULL", Name = "Discharged Loan Code" },
				new FahAlert() { Id = "5", Description = "NULL", Name = "Default Loan Flag" },
				new FahAlert() { Id = "6", Description = "NULL", Name = "Additional Unsubsidized Loan Flag(s)" },
				new FahAlert() { Id = "7", Description = "NULL", Name = "Reaffirmation Flag" },
				new FahAlert() { Id = "8", Description = "NULL", Name = "Veterans Administration Discharge" },
				new FahAlert() { Id = "9", Description = "NULL", Name = "Undergraduate Loans Remaining Eligibility - Subsidized" },
				new FahAlert() { Id = "AcademicLevel", Description = "NULL", Name = "Acad. Level" },
				new FahAlert() { Id = "ACG", Description = "NULL", Name = "ACG Grant" },
				new FahAlert() { Id = "ACGHistory", Description = "NULL", Name = "ACG Grant History" },
				new FahAlert() { Id = "AnnualAwards", Description = "NULL", Name = "Annual Awards" },
				new FahAlert() { Id = "ApprovedAmount", Description = "NULL", Name = "Approved Amount" },
				new FahAlert() { Id = "AwardAmount", Description = "NULL", Name = "Award Amount" },
				new FahAlert() { Id = "AwardYear", Description = "NULL", Name = "Award Year" },
				new FahAlert() { Id = "AYDates", Description = "NULL", Name = "Academic Year Dates" },
				new FahAlert() { Id = "AYLevel", Description = "NULL", Name = "Academic Year Level" },
				new FahAlert() { Id = "AYPercentUsed", Description = "NULL", Name = "% of Sched. Award Used by Award Year" },
				new FahAlert() { Id = "CIP", Description = "NULL", Name = "CIP" },
				new FahAlert() { Id = "DisbursedAmount", Description = "NULL", Name = "Disbursed Amount" },
				new FahAlert() { Id = "EFC", Description = "NULL", Name = "EFC" },
				new FahAlert() { Id = "GradeLevel", Description = "For Graduate", Name = "Grade Level Eligibility - Up to Cost of Attendance" },
				new FahAlert() { Id = "GradReceived", Description = "NULL", Name = "Total Graduate Received" },
				new FahAlert() { Id = "GradRemain", Description = "NULL", Name = "Remaining Graduate Eligibility" },
				new FahAlert() { Id = "Graduate", Description = "NULL", Name = "Graduate Remaining Loan Eligibility (Independent Only)" },
				new FahAlert() { Id = "GraduateLoans", Description = "NULL", Name = "Graduate Loans Remaining Eligibility" },
				new FahAlert() { Id = "GraduatePlusBalance", Description = "NULL", Name = "Graduate PLUS Total Outstanding Principal Balance" },
				new FahAlert() { Id = "Grants", Description = "NULL", Name = "Grant History" },
				new FahAlert() { Id = "HSProgram", Description = "NULL", Name = "HS Program" },
				new FahAlert() { Id = "LEU", Description = "NULL", Name = "Pell Lifetime Eligibility Used" },
				new FahAlert() { Id = "LoanAggregateLimits", Description = "NULL", Name = "Loan Aggregate Limits" },
				new FahAlert() { Id = "LoanAmount", Description = "NULL", Name = "Loan Amount" },
				new FahAlert() { Id = "LoanCode", Description = "NULL", Name = "Loan Code" },
				new FahAlert() { Id = "LoanDates", Description = "NULL", Name = "Loan Period Dates" },
				new FahAlert() { Id = "LoanFlag", Description = "NULL", Name = "Additional Unsub Flag" },
				new FahAlert() { Id = "LoanHistory", Description = "NULL", Name = "Loan History" },
				new FahAlert() { Id = "Loans", Description = "NULL", Name = "Other Funding Loan History" },
				new FahAlert() { Id = "LoanStatus", Description = "NULL", Name = "Current Loan Status Code" },
				new FahAlert() { Id = "LoanStatusDate", Description = "NULL", Name = "Status Date" },
				new FahAlert() { Id = "LoanType", Description = "NULL", Name = "Loan Type" },
				new FahAlert() { Id = "MEP", Description = "NULL", Name = "Maximum Eligibility Period (MEP)" },
				new FahAlert() { Id = "NameHistory", Description = "NULL", Name = "Name History" },
				new FahAlert() { Id = "OpenAcademicYear", Description = "When the academic year is not provided by NSLDS", Name = " the profiled definition of academic year in weeks is used.Some students may also have capitalized interest or refunds applied to each loan and may require additional research to accurately determine the student’s eligibility." },
				new FahAlert() { Id = "OpenAY", Description = "NULL", Name = "Open AY" },
				new FahAlert() { Id = "OpenGraduate", Description = "NULL", Name = "Graduate Open Loan Period Remaining Eligibility (Independent Only)" },
				new FahAlert() { Id = "OpenUndergradDependent", Description = "NULL", Name = "Undergraduate Open Loan Period Remaining Eligibility (Dependent)" },
				new FahAlert() { Id = "OpenUndergradIndependent", Description = "NULL", Name = "Undergraduate Open Loan Period Remaining Eligibility (Independent)" },
				new FahAlert() { Id = "OtherFunding", Description = "NULL", Name = "Other Funding" },
				new FahAlert() { Id = "OutstandingPrincipalBal", Description = "NULL", Name = "Outstanding Principal Balance" },
				new FahAlert() { Id = "ParentPlusBalance", Description = "NULL", Name = "Parent PLUS Total Outstanding Principal Balance" },
				new FahAlert() { Id = "Pell", Description = "600% Maximum Usage", Name = "Pell Grant" },
				new FahAlert() { Id = "PellHistory", Description = "NULL", Name = "Pell Grant History" },
				new FahAlert() { Id = "PellLEU", Description = "NULL", Name = "Pell LEU Remaining Eligibility" },
				new FahAlert() { Id = "PendingDisbursement", Description = "NULL", Name = "Pending Disbursement" },
				new FahAlert() { Id = "PeriodDates", Description = "NULL", Name = "Loan Period Dates" },
				new FahAlert() { Id = "PerkinsAYDisbursed", Description = "NULL", Name = "Perkins Loans Current Award Year Disbursed" },
				new FahAlert() { Id = "PerkinsBalance", Description = "NULL", Name = "Perkins Loans Total Outstanding Principal Balance" },
				new FahAlert() { Id = "PrincipalBalance", Description = "NULL", Name = "Aggregate Outstanding Principal Balance" },
				new FahAlert() { Id = "Remain", Description = "NULL", Name = "Estimated Remaining Pell Eligibility" },
				new FahAlert() { Id = "REP", Description = "NULL", Name = "Remaining Eligibility Period (REP)" },
				new FahAlert() { Id = "School", Description = "NULL", Name = "School" },
				new FahAlert() { Id = "Smart", Description = "NULL", Name = "SMART Grant" },
				new FahAlert() { Id = "SmartHistory", Description = "NULL", Name = "SMART Grant History" },
				new FahAlert() { Id = "SubLoanRemain", Description = "NULL", Name = "Subsidized Loans" },
				new FahAlert() { Id = "SubUsage", Description = "NULL", Name = "Subsidized Used" },
				new FahAlert() { Id = "SULA", Description = "The REP is estimated based on NSLDS results. Verify the REP based on the results in the Common Origination and Disbursement (COD) website.", Name = "Subsidized Usage Limit Applies" },
				new FahAlert() { Id = "Teach", Description = "NULL", Name = "TEACH Grant" },
				new FahAlert() { Id = "TeachBalance", Description = "NULL", Name = "Teach Loan (Converted Grant) Total Outstanding Principal Balance" },
				new FahAlert() { Id = "TeachHistory", Description = "NULL", Name = "TEACH Grant History" },
				new FahAlert() { Id = "TotalAwarded", Description = "NULL", Name = "Total Amount Awarded" },
				new FahAlert() { Id = "TotalLoanHistory", Description = "NULL", Name = "Total Loan History" },
				new FahAlert() { Id = "TotalPercentUsed", Description = "NULL", Name = "Total % of Eligibility Used" },
				new FahAlert() { Id = "TotalReceived", Description = "NULL", Name = "Total Amount Disbursed" },
				new FahAlert() { Id = "TotalRemain", Description = "NULL", Name = "Total Remaining Eligibility" },
				new FahAlert() { Id = "UndergradDependent", Description = "For dependent student", Name = "Undergraduate Dependent Remaining Loan Eligibility" },
				new FahAlert() { Id = "UndergradIndependent", Description = "For independent student or dependent with PLUS denial", Name = "Undergraduate Independent Remaining Loan Eligibility" },
				new FahAlert() { Id = "UndergradReceived", Description = "NULL", Name = "Total Undergraduate Received" },
				new FahAlert() { Id = "UndergradRemain", Description = "NULL", Name = "Remaining Undergraduate Eligibility" },
				new FahAlert() { Id = "UndergraduateLoans", Description = "NULL", Name = "Undergraduate Loans Remaining Eligibility" },
				new FahAlert() { Id = "UnsubLoanRemain", Description = "NULL", Name = "Unsubsidized Loans" },
				new FahAlert() { Id = "UnusualEnrollment", Description = "NULL", Name = "Unusual Enrollment History" },
				new FahAlert() { Id = "ValidUntil", Description = "Date after which the financial aid history will expire", Name = "History Valid Until" }
			};
			return fa.AsQueryable();
		}

		public static IQueryable<FahField> GetTestFahFieldLookups()
		{
			List<FahField> ff = new List<FahField>()
			{
				new FahField() { Id =  "AcademicLevel", Description = "Student’s academic level at the school when the loan was disbursed.", Name = "Academic Level" },
				new FahField() { Id =  "AcceptedVerification", Description = "Accepted verification status.", Name = "Accepted Verification Status" },
				new FahField() { Id =  "ACGChange", Description = "Indicates change to ACG information on one or more grants.", Name = "ACG Change Flag" },
				new FahField() { Id =  "ActiveBankruptcy", Description = "Indicates one or more active bankruptcy loans. ", Name = "Active Bankruptcy Flag" },
				new FahField() { Id =  "AddEligibility", Description = "Indicator of the student’s eligibility for two Pell grants in an award year.  ", Name = "Additional Eligibility Indicator (AEI)" },
				new FahField() { Id =  "AdditionalUnsubLoan", Description = "Additional Unsubsidized Loan flag.", Name = "Additional Unsubsidized Loan Flag" },
				new FahField() { Id =  "AggregateChange", Description = "Indicates changed Aggregate Amount information. ", Name = "Aggregate Change Flag" },
				new FahField() { Id =  "AwardAmount", Description = "Accepted origination amount.", Name = "Award Amount" },
				new FahField() { Id =  "AwardId", Description = "Indicates the Award ID, provided by COD, which identifies an ACG, SMART or TEACH grant.", Name = "Award ID" },
				new FahField() { Id =  "AwardYear", Description = "The Award Year for the grant program, beginning July 1 and ending June 30 of following year.", Name = "Award Year" },
				new FahField() { Id =  "AYBeginDate", Description = "The date when the student's academic year begins (or has begun) for the period covered by the loan. Format is CCYYMMDD.  Value is date or N/A if date is not available.", Name = "Academic Year Begin Date" },
				new FahField() { Id =  "AYEndDate", Description = "The date when the student's academic year ended (or will end) for the period covered by the loan. Format is CCYYMMDD.  Value is date or N/A if date is not available.", Name = "Academic Year End Date" },
				new FahField() { Id =  "AYLevel", Description = "Indicates the student’s grade level for ACG, SMART and TEACH grants.", Name = "Academic Year Level " },
				new FahField() { Id =  "CalcCombinedAmount", Description = "Amount included in Combined Aggregate calculation.", Name = "Calculated Combined Aggregate OPB" },
				new FahField() { Id =  "CalcSubAmount", Description = "Amount included in Subsidized Aggregate calculation.", Name = "Calculated Subsidized Aggregate OPB" },
				new FahField() { Id =  "CalcUnsubAmount", Description = "Amount included in Unsubsidized Aggregate calculation. ", Name = "Calculated Unsubsidized Aggregate OPB" },
				new FahField() { Id =  "CapitalInterest", Description = "Capitalized Interest flag.", Name = "Capitalized Interest Flag" },
				new FahField() { Id =  "CIPCode", Description = "Indicates a student’s major course of study; the Classification of Instructional Programs (CIP) designated code for SMART grants.", Name = "CIP Code" },
				new FahField() { Id =  "CODPostedDate", Description = "Date disbursement was posted to the COD system.", Name = "Posted by COD" },
				new FahField() { Id =  "CombinedPendingDisb", Description = "Pending disbursements for subsidized and unsubsidized loan types (D0, D1, D2, SF, and SU).", Name = "Aggregate Combined Pending Disbursement (Undergraduate and Graduate)" },
				new FahField() { Id =  "CombinedPrincipalBal", Description = "Outstanding principal balance for subsidized and unsubsidized loan types (D0, D1, D2, D5, D6, FI, RF, subsidized and non-subsidized SF, SL, and SU). Includes the total amount of a consolidation loan, excluding the calculated share that is considered to be", Name = "Aggregate Combined Outstanding Principal Balance (Undergraduate and Graduate)" },
				new FahField() { Id =  "CombinedTotal", Description = "Total of Aggregate Combined Outstanding Principal Balance and Aggregate Combined Pending Disbursement. ", Name = "Aggregate Combined Total (Undergraduate and Graduate)" },
				new FahField() { Id =  "ConfirmSubDate", Description = "Date the subsidy status went into effect as reported to NSLDS.  Format is CCYYMMDD.  Value is date or N/A if date is not available.", Name = "Subsidy Status Date" },
				new FahField() { Id =  "ConfirmSubStatus", Description = "Indicates the current status of a SULA eligible loan’s subsidy as reported by the servicer.", Name = "Confirmed Loan Subsidy Status  " },
				new FahField() { Id =  "ContactType", Description = "Contact Type code. ", Name = "Contact Type" },
				new FahField() { Id =  "CurrentDOB", Description = "Date of Birth from NSLDS of the student for whom the FAH or Alert is being generated. ", Name = "Current Date of Birth" },
				new FahField() { Id =  "CurrentFirstName", Description = "Current first name from NSLDS of the student for whom the FAH or Alert is being generated.", Name = "Current First Name" },
				new FahField() { Id =  "CurrentGACode", Description = "Current Guaranty Agency code or N/A if not applicable.", Name = "Current GA Code" },
				new FahField() { Id =  "CurrentLastName", Description = "Current last name from NSLDS of the student for whom the FAH or Alert is being generated.", Name = "Current Last Name" },
				new FahField() { Id =  "DataProviderID", Description = "For FFEL and Perkins loans, Data Provider Loan ID used by data provider (Guaranty Agency or Debt Management Collection Service for FFEL or Perkins held loans) for internal loan identification. For Direct Loans and FFEL loans purchased by ED, Award ID used", Name = "Data Provider Loan ID/Award ID" },
				new FahField() { Id =  "DefaultedLoan", Description = "Indicates one or more defaulted loans. ", Name = "Defaulted Loan Flag" },
				new FahField() { Id =  "DirectLoanPlusGradMPN", Description = "Direct Loan PLUS Graduate/Professional Master Promissory Note Flag.", Name = "Direct Loan PLUS Graduate/Professional MPN Flag" },
				new FahField() { Id =  "DirectLoanPlusMPN", Description = "Direct Loan PLUS Master Promissory Note Flag. ", Name = "Direct Loan PLUS MPN Flag" },
				new FahField() { Id =  "DirectStaffordMPN", Description = "Direct Loan Stafford Master Promissory Note Flag.", Name = "Direct Stafford MPN Flag" },
				new FahField() { Id =  "DisbAmount", Description = "The amount of the Federal grant the school has disbursed to the student.", Name = "Disbursed Amount" },
				new FahField() { Id =  "DischargedLoanCode", Description = "Indicates one or more discharged loans.", Name = "Discharged Loan Code" },
				new FahField() { Id =  "DOB", Description = "Date of Birth of student submitted. ", Name = "Date of Birth" },
				new FahField() { Id =  "EligibilityCode", Description = "Indicates the eligibility payment code for ACG.", Name = "Eligibility Payment Code" },
				new FahField() { Id =  "EligibilityUsed", Description = "Pell’s percent of scheduled award used by award year.  ACG and SMART’s percent eligibility used by scheduled award.", Name = "Percent of Eligibility Used " },
				new FahField() { Id =  "FamilyContribution", Description = "Index produced by the Congressional Methodology (CM) needs analysis assessment.", Name = "Expected Family Contribution" },
				new FahField() { Id =  "FirstName", Description = "First name of student submitted. ", Name = "First Name" },
				new FahField() { Id =  "FirstNameHistory", Description = "Other first name used by the student for whom the FAH or Alert is provided. ", Name = "First Name History" },
				new FahField() { Id =  "FirstTimePell", Description = "Indicator that Pell award is the student’s first actual Pell disbursement.  ", Name = "First Time Pell Indicator" },
				new FahField() { Id =  "Fraud", Description = "Indicates fraud on one or more loans or overpayments.", Name = "Fraud Flag" },
				new FahField() { Id =  "GradAY", Description = "Award year used in the student’s graduate loan limits determination.", Name = "Graduate Award Year" },
				new FahField() { Id =  "GradCombinedLoanLimit", Description = "Flag indicating the condition of the Aggregate Total combined loan limit for a borrower with cumulative balances having undergraduate and graduate loans.", Name = "Graduate Combined Loan Limit Flag" },
				new FahField() { Id =  "GradCombinedPendingDisb", Description = "Pending disbursements for graduate subsidized and unsubsidized loan types (D0, D1, D2, SF, and SU).", Name = "Graduate Aggregate Combined Pending Disbursement " },
				new FahField() { Id =  "GradCombinedPrincipalBal", Description = "Outstanding principal balance for graduate subsidized and unsubsidized loan types (D0, D1, D2, D5, D6, FI, RF, subsidized and non-subsidized SF, SL, and SU). Includes the total amount of a graduate consolidation loan, excluding the calculated share that i", Name = "Graduate Aggregate Combined Outstanding Principal Balance" },
				new FahField() { Id =  "GradCombinedTotal", Description = "Total of Graduate Aggregate Combined Outstanding Principal Balance and Graduate Aggregate Combined Pending Disbursements. ", Name = "Graduate Aggregate Combined Total " },
				new FahField() { Id =  "GradDependency", Description = "Indicator of the dependency used in the student’s graduate loan limits determination.", Name = "Graduate Dependency Indicator" },
				new FahField() { Id =  "GradEligibilityUsed", Description = "TEACH grant’s awarded percent used by Graduate Academic Levels.", Name = "Graduate % Eligibility Used" },
				new FahField() { Id =  "GradRemainingAmount", Description = "The remaining eligible amount by Graduate Academic Levels.", Name = "Graduate Remaining Amount" },
				new FahField() { Id =  "GradSubLoanLimit", Description = "Flag indicating the condition of the Aggregate Total for subsidized loan limit (Loan types include: D0, D1, D6, subsidized SF, and calculated share of consolidation loan considered to be subsidized.) for a borrower with cumulative balances having undergra", Name = "Graduate Subsidized Loan Limit Flag" },
				new FahField() { Id =  "GradSubPendingDisb", Description = "Pending disbursements for graduate subsidized loan types (D0, D1 and subsidized SF). ", Name = "Graduate Aggregate Subsidized Pending Disbursement " },
				new FahField() { Id =  "GradSubPrincipalBal", Description = "Outstanding principal balance for graduate subsidized loan types (D0, D1, D6, and subsidized SF). Includes calculated share of a graduate consolidation loan that is considered subsidized. ", Name = "Graduate Aggregate Subsidized Outstanding Principal Balance" },
				new FahField() { Id =  "GradSubTotal", Description = "Total of Graduate Aggregate Subsidized Outstanding Principal Balance and Graduate Aggregate Subsidized Pending Disbursements. ", Name = "Graduate Aggregate Subsidized Total " },
				new FahField() { Id =  "GradTeachTotalDisb", Description = "Aggregate Graduate TEACH grant disbursed amounts for the following Academic Levels:", Name = "Aggregate Total TEACH Grant Graduate Disbursement Amount" },
				new FahField() { Id =  "GradUnallocPrincipalBal", Description = "Outstanding principal balance for graduate consolidation loan amount determined to be unallocated.", Name = "Graduate Aggregate Consolidation Loans, Unallocated Outstanding Principal Balance" },
				new FahField() { Id =  "GradUnallocTotal", Description = "Graduate Aggregate Total for consolidation loan amount determined to be unallocated. ", Name = "Graduate Aggregate Consolidation Loans, Unallocated Total " },
				new FahField() { Id =  "GradUnsubPendingDisb", Description = "Pending disbursements for graduate unsubsidized loan types (D2 and SU). ", Name = "Graduate Aggregate Unsubsidized Pending Disbursement " },
				new FahField() { Id =  "GradUnsubPrincipalBal", Description = "Outstanding principal balance for graduate unsubsidized loan types (D2, D5, FI, RF, non-subsidized SF, SL, and SU). Includes calculated share of a graduate consolidation loan that is considered unsubsidized. ", Name = "Graduate Aggregate Unsubsidized Outstanding Principal Balance" },
				new FahField() { Id =  "GradUnsubTotal", Description = "Total of Graduate Aggregate Unsubsidized Outstanding Principal Balance and Graduate Aggregate Unsubsidized Pending Disbursements. ", Name = "Graduate Aggregate Unsubsidized Total " },
				new FahField() { Id =  "GrantChangeFlag", Description = "Indicates change to this grant record. ", Name = "Grant Change Flag" },
				new FahField() { Id =  "GrantContact", Description = "Contact for grant overpayment. ", Name = "Contact" },
				new FahField() { Id =  "GrantSchoolCode", Description = "An 8-digit OPEID code used to identify the school attended by the student with the grant. Last 2 digits equal 00 if no branch code.", Name = "School Code" },
				new FahField() { Id =  "GrantSequence", Description = "The grant identifying sequence number. ", Name = "Grant Sequence Number" },
				new FahField() { Id =  "GrantType", Description = "Indicates a 2-character code that identifies the grant type reported for the student.", Name = "Grant Type" },
				new FahField() { Id =  "HSProgramCode", Description = "Indicates the high school program code for ACG.  ", Name = "High School Program Code" },
				new FahField() { Id =  "LastDisbAmount", Description = "Amount of last disbursement", Name = "Last Disbursement Amount" },
				new FahField() { Id =  "LastDisbDate", Description = "Date school made the latest disbursement.", Name = "Latest Disbursement Date" },
				new FahField() { Id =  "LastLoanDisbDate", Description = "Date latest loan disbursement was made.", Name = "Last Disbursement Date" },
				new FahField() { Id =  "LastName", Description = "Last name of student submitted. ", Name = "Last Name" },
				new FahField() { Id =  "LastNameHistory", Description = "Other last name used by the student for whom the FAH or Alert is provided. ", Name = "Last Name History" },
				new FahField() { Id =  "LenderCode", Description = "Current Lender code or N/A if not applicable.", Name = "Lender Code" },
				new FahField() { Id =  "LenderServicer", Description = "Current Lender Servicer code or N/A if not applicable.", Name = "Lender Servicer Code" },
				new FahField() { Id =  "LifeEligibilityUsed", Description = "The Lifetime Eligibility Used (LEU) for Pell grants expressed as a decimal  ", Name = "Lifetime Eligibility Used (LEU)" },
				new FahField() { Id =  "LoanAmount", Description = "Guaranteed/approved loan amount.", Name = "Loan Amount" },
				new FahField() { Id =  "LoanChange", Description = "Indicates changed information on one or more loans. ", Name = "Loan Change Flag" },
				new FahField() { Id =  "LoanContact", Description = "Code indicating the agency to be contacted for this loan.", Name = "Contact" },
				new FahField() { Id =  "LoanDate", Description = "Date of loan guarantee/approval. ", Name = "Loan Date " },
				new FahField() { Id =  "LoanPeriodBeginDate", Description = "Date the enrollment period begins for this loan.", Name = "Loan Period Begin Date" },
				new FahField() { Id =  "LoanPeriodEndDate", Description = "Date the enrollment period ends for this loan.", Name = "Loan Period End Date" },
				new FahField() { Id =  "LoanRecChange", Description = "Indicates change to this loan record. There will be a space for FAH records.", Name = "Loan Change Flag" },
				new FahField() { Id =  "LoanSchoolCode", Description = "An 8-digit OPEID code used to identify the school attended by the student when the loan was originated. Last 2 digits equal 00 if no branch code. ", Name = "School Code" },
				new FahField() { Id =  "LoanStatusCode", Description = "Code used to identify the current status of a student’s loan.", Name = "Current Loan Status Code" },
				new FahField() { Id =  "LoanStatusDate", Description = "Date the current loan status code became effective. Format is CCYYMMDD.", Name = "Current Loan Status Date" },
				new FahField() { Id =  "LoanTypeCode", Description = "Code indicating the type of loan.", Name = "Loan Type Code" },
				new FahField() { Id =  "MiddleInitialHistory", Description = "Other middle initial used by the student for whom the FAH or Alert is provided, if available.", Name = "Middle Initial History" },
				new FahField() { Id =  "NetLoanAmount", Description = "Amount of loan/guaranty minus total amount of cancellations and refunds.", Name = "Net Loan Amount" },
				new FahField() { Id =  "OverDisbAY", Description = "Award Year on which the overpayment was disbursed.", Name = "Award Year" },
				new FahField() { Id =  "Overpayment", Description = "One-character code that identifies the status of the overpayment.", Name = "Overpayment Indicator" },
				new FahField() { Id =  "OverpaymentType", Description = "A 2-character code that identifies the type of overpayment(s) reported for the student.", Name = "Overpayment Type" },
				new FahField() { Id =  "PellChange", Description = "Indicates change to Pell grant information on one or more grants. ", Name = "Pell Change Flag" },
				new FahField() { Id =  "PellLifeLimit", Description = "Indicates the limit reached for the Pell Grant Lifetime Eligibility Used.", Name = "LEU Limit Indicator" },
				new FahField() { Id =  "PerkinsCancelCode", Description = "Loan cancellation reasons. ", Name = "Perkins Cancellation Type Code" },
				new FahField() { Id =  "PerkinsCurrentAYDisb", Description = "Total Perkins loan (DU, EU, NU, PU, and IC) disbursements for award year (July-June). ", Name = "Perkins Current Award Year Disbursement" },
				new FahField() { Id =  "PerkinsTotalPrincipalBal", Description = "Total Perkins loan (DU, EU, NU, PU, and IC) outstanding principal balances. ", Name = "Perkins Total Outstanding Principal Balance" },
				new FahField() { Id =  "PlusLoanPrincipalBal", Description = "Outstanding principal balance for PLUS loan types (PL, D4, and D7). Will be populated when the borrower is the PLUS loan holder", Name = "Aggregate PLUS Loans Outstanding Principal Balance" },
				new FahField() { Id =  "PlusLoanTotal", Description = "Total for PLUS loan types (PL, D4, and D7). Will be populated when the borrower is the PLUS loan holder.", Name = "Aggregate PLUS Loans Total" },
				new FahField() { Id =  "PlusProPrincipalBal", Description = "Outstanding principal balance for PLUS Graduate/Prof. loan types (D3 and GB).", Name = "Aggregate PLUS Graduate/Professional Outstanding Principal Balance" },
				new FahField() { Id =  "PlusProTotal", Description = "Total for PLUS Graduate/Prof. loan types (D3 and GB).", Name = "Aggregate PLUS Graduate/Professional Total" },
				new FahField() { Id =  "Post911DeceasedDep", Description = "Indicator for a Post 9/11 Deceased Veteran Dependent.", Name = "Post 911 Deceased Veteran Dependent Indicator" },
				new FahField() { Id =  "PrincipalBal", Description = "Amount of outstanding principal balance. ", Name = "Outstanding Principal Balance" },
				new FahField() { Id =  "PrincipalDate", Description = "Date the outstanding principal balance was last updated. Format is CCYYMMDD.", Name = "Outstanding Principal Balance Date" },
				new FahField() { Id =  "Reaffirmation", Description = "Indicates if the loan has an active reaffirmation.", Name = "Reaffirmation flag" },
				new FahField() { Id =  "ReceivedOn", Description = "Date Received", Name = "Date Received" },
				new FahField() { Id =  "SatisfactoryRepayLoan", Description = "Indicates one or more loans with satisfactory repayment arrangements. ", Name = "Loan Satisfactory Repayment Arrangements Flag" },
				new FahField() { Id =  "SchedAmount", Description = "Scheduled amount of the Federal Pell grant. TEACH grant scheduled award is $4,000.", Name = "Scheduled Amount" },
				new FahField() { Id =  "SMARTChange", Description = "Indicates change to SMART grant information on one or more grants.", Name = "SMART Change Flag" },
				new FahField() { Id =  "StartDate", Description = "Start Date", Name = "Start Date" },
				new FahField() { Id =  "SubPendingDisb", Description = "Pending disbursements for subsidized loan types (D0, D1 and subsidized SF). ", Name = "Aggregate Subsidized Pending Disbursement (Undergraduate and Graduate)" },
				new FahField() { Id =  "SubPrincipalBal", Description = "Outstanding principal balance for subsidized loan types (D0, D1, D6, and subsidized SF). Includes calculated share of a consolidation loan that is considered subsidized. ", Name = "Aggregate Subsidized Outstanding Principal Balance (Undergraduate and Graduate)" },
				new FahField() { Id =  "SubTotal", Description = "Total of Aggregate Subsidized Outstanding Principal Balance and Aggregate Subsidized Pending Disbursement. ", Name = "Aggregate Subsidized Total (Undergraduate and Graduate)" },
				new FahField() { Id =  "SubUsagePeriod", Description = "Indicates the total time during which the student has received Direct Subsidized Loans as reported to NSLDS by COD. This field contains numeric six-digit values, 000v000 to 999v999, where “v” is an implied decimal and is excluded from the output.", Name = "Subsidized Usage Period " },
				new FahField() { Id =  "SulaFlag", Description = "Subsidized Usage Limit Applies (SULA) indicator on loan.", Name = "SULA Flag" },
				new FahField() { Id =  "TEACHConversionDate", Description = "Date the TEACH grant was converted to a loan.", Name = "TEACH grant conversion date" },
				new FahField() { Id =  "TEACHConverted", Description = "Indicates TEACH grant was converted to a loan. ", Name = "TEACH grant converted to loan flag" },
				new FahField() { Id =  "TeachGrantChange", Description = "Indicates changed TEACH grant Aggregate Amount information. ", Name = "TEACH Grant Aggregates Change Flag" },
				new FahField() { Id =  "TeachGrantConverted", Description = "Indicates a TEACH grant was converted to a TEACH loan on one or more grants.", Name = "TEACH Grant Converted to Loan Flag" },
				new FahField() { Id =  "TeachGrantDataChange", Description = "Indicates change to TEACH grant information on one or more grants.", Name = "TEACH Grant Data Change Flag" },
				new FahField() { Id =  "TeachLoanChange", Description = "Indicates changed TEACH loan Aggregate Amount information. ", Name = "TEACH Loan Aggregate Change Flag" },
				new FahField() { Id =  "TeachLoanPrincipalBal", Description = "Outstanding principal balance for TEACH unsubsidized loan type (D8).  ", Name = "TEACH Loan OPB" },
				new FahField() { Id =  "TeachLoanTotal", Description = "Total of Aggregate TEACH Unsubsidized loan Outstanding Principal Balance. ", Name = "TEACH Loan Total" },
				new FahField() { Id =  "TotalDisb", Description = "Cumulative amount disbursed. ", Name = "Total Disbursement Amount" },
				new FahField() { Id =  "TotalEligibilityUsed", Description = "The total percent of eligibility used for ACG and SMART grants.  ", Name = "Total Percent Eligibility Used by Academic Year Level" },
				new FahField() { Id =  "TransNumber", Description = "Transaction number on the SAR or ISIR for the payment accepted by the school.", Name = "Transaction Number" },
				new FahField() { Id =  "UnallocatedAmount", Description = "Amount that could not be determined to be subsidized, unsubsidized or Perkins.", Name = "Consolidation Unallocated Aggregate OPB" },
				new FahField() { Id =  "UnAllocPrincipalBal", Description = "Aggregate Outstanding principal balance for Consolidation Loans, Unallocated.", Name = "Aggregate Consolidation Loans, Unallocated Outstanding Principal Balance (Undergraduate and Graduate)" },
				new FahField() { Id =  "UnAllocPrincipalTotal", Description = "Aggregate Total for Consolidation Loans, Unallocated.", Name = "Aggregate Consolidation Loans, Unallocated Total (Undergraduate and Graduate)" },
				new FahField() { Id =  "UndergradAY", Description = "Award year used in the student’s undergraduate loan limits determination.", Name = "Undergraduate Award Year" },
				new FahField() { Id =  "UnderGradCombinedLoanLimit", Description = "Flag indicating the condition of the Aggregate Total` combined loan limit at the undergraduate level.", Name = "Undergraduate Combined Loan Limit Flag" },
				new FahField() { Id =  "UndergradCombinedPendingDisb", Description = "Pending disbursements for undergraduate subsidized and unsubsidized loan types (D0, D1, D2, SF, and SU).", Name = "Undergraduate Aggregate Combined Pending Disbursement " },
				new FahField() { Id =  "UndergradCombinedPrincipalBal", Description = "Outstanding principal balance for undergraduate subsidized and unsubsidized loan types (D0, D1, D2, D5, D6, FI, RF, subsidized and non-subsidized SF, SL, and SU). Includes the total amount of an undergraduate consolidation loan, excluding the calculated s", Name = "Undergraduate Aggregate Combined Outstanding Principal Balance" },
				new FahField() { Id =  "UndergradCombinedTotal", Description = "Total of Undergraduate Aggregate Combined Outstanding Principal Balance and Undergraduate Aggregate Combined Pending Disbursements. ", Name = "Undergraduate Aggregate Combined Total " },
				new FahField() { Id =  "UndergradDependency", Description = "Indicator of the dependency used in the student’s undergraduate loan limits determination.", Name = "Undergraduate Dependency Indicator" },
				new FahField() { Id =  "UndergradEligibilityUsed", Description = "TEACH grant’s awarded percent used by Undergraduate/Post Baccalaureate Academic Levels.", Name = "Undergraduate % Eligibility Used" },
				new FahField() { Id =  "UndergradRemainingAmount", Description = "The remaining eligible amount by Undergraduate/Post Baccalaureate Academic Levels.", Name = "Undergraduate Remaining Amount" },
				new FahField() { Id =  "UnderGradSubLoanLimit", Description = "Flag indicating the condition of the Aggregate Total for subsidized loan limit (Loan types include: DO, D1, D6, subsidized SF, and calculated share of consolidation loan considered to be subsidized.) at the undergraduate level.", Name = "Undergraduate Subsidized Loan Limit Flag" },
				new FahField() { Id =  "UndergradSubPendingDisb", Description = "Pending disbursements for undergraduate subsidized loan types (D0, D1 and subsidized SF). ", Name = "Undergraduate Aggregate Subsidized Pending Disbursement " },
				new FahField() { Id =  "UndergradSubPrincipalBal", Description = "Outstanding principal balance for undergraduate subsidized loan types (D0, D1, D6, and subsidized SF). Includes calculated share of an undergraduate consolidation loan that is considered subsidized. ", Name = "Undergraduate Aggregate Subsidized Outstanding Principal Balance" },
				new FahField() { Id =  "UndergradSubTotal", Description = "Total of Undergraduate Aggregate Subsidized Outstanding Principal Balance and Undergraduate Aggregate Subsidized Pending Disbursements. ", Name = "Undergraduate Aggregate Subsidized Total " },
				new FahField() { Id =  "UndergradTeachDisbTotal", Description = "Aggregate Undergraduate/Post Baccalaureate TEACH grant disbursed amounts for the following Academic Levels:", Name = "Aggregate Total TEACH Grant Undergraduate Disbursement Amount" },
				new FahField() { Id =  "UndergradUnallocPrincipalBal", Description = "Outstanding principal balance for undergraduate consolidation loan amount determined to be unallocated.", Name = "Undergraduate Aggregate Consolidation Loans, Unallocated Outstanding Principal Balance" },
				new FahField() { Id =  "UndergradUnallocTotal", Description = "Undergraduate Aggregate Total for consolidation loan amount determined to be unallocated. ", Name = "Undergraduate Aggregate Consolidation Loans, Unallocated Total " },
				new FahField() { Id =  "UndergradUnsubPendingDisb", Description = "Pending disbursements for undergraduate unsubsidized loan types (D2 and SU). ", Name = "Undergraduate Aggregate Unsubsidized Pending Disbursement " },
				new FahField() { Id =  "UndergradUnsubPrincipalBal", Description = "Outstanding principal balance for undergraduate unsubsidized loan types (D2, D5, FI, RF, non-subsidized SF, SL, and SU). Includes calculated share of an undergraduate consolidation loan that is considered unsubsidized. ", Name = "Undergraduate Aggregate Unsubsidized Outstanding Principal Balance" },
				new FahField() { Id =  "UndergradUnsubTotal", Description = "Total of Undergraduate Aggregate Unsubsidized Outstanding Principal Balance and Undergraduate Aggregate Unsubsidized Pending Disbursements. ", Name = "Undergraduate Aggregate Unsubsidized Total " },
				new FahField() { Id =  "UnSubPendingDisb", Description = "Pending disbursements for unsubsidized loan types (D2 and SU). ", Name = "Aggregate Unsubsidized Pending Disbursement (Undergraduate and Graduate)" },
				new FahField() { Id =  "UnSubPrincipalBal", Description = "Outstanding principal balance for unsubsidized loan types (D2, D5, FI, RF, non-subsidized SF, SL, and SU) Includes calculated share of a consolidation loan that is considered unsubsidized. ", Name = "Aggregate Unsubsidized Outstanding Principal Balance (Undergraduate and Graduate)" },
				new FahField() { Id =  "UnSubTotal", Description = "Total of Aggregate Unsubsidized Outstanding Principal Balance and Aggregate Unsubsidized Pending Disbursement. ", Name = "Aggregate Unsubsidized Total (Undergraduate and Graduate)" },
				new FahField() { Id =  "UnusualEnrollHistory", Description = "Indicates a student’s Pell Grant and loan awarding activity pattern that looks suspicious.", Name = "Unusual Enrollment History Indicator" },
				new FahField() { Id =  "ValidUntil", Description = "History Valid Until", Name = "History Valid Until" }

			};

			return ff.AsQueryable();
		}

		public static IQueryable<FahCode> GetTestFahCodeLookups()
		{
			List<FahCode> fc = new List<FahCode>()
			{
				new FahCode() {FahFieldId =  "ActiveBankruptcy", Code = "TRUE", Name = "Y = Indicates one or more active bankruptcy loans" },
				new FahCode() {FahFieldId =  "AdditionalUnsubLoan", Code = "B", Name = "B = PLUS Denial and Health Loan Program" },
				new FahCode() {FahFieldId =  "AdditionalUnsubLoan", Code = "H", Name = "H = Health Loan Program" },
				new FahCode() {FahFieldId =  "AdditionalUnsubLoan", Code = "P", Name = "P = PLUS Denial" },
				new FahCode() {FahFieldId =  "DefaultedLoan", Code = "TRUE", Name = "Y = Indicates one or more defaulted loans" },
				new FahCode() {FahFieldId =  "DischargedLoanCode", Code = "C", Name = "C = Conditional" },
				new FahCode() {FahFieldId =  "DischargedLoanCode", Code = "D", Name = "D = Death" },
				new FahCode() {FahFieldId =  "DischargedLoanCode", Code = "M", Name = "M = Multiple " },
				new FahCode() {FahFieldId =  "DischargedLoanCode", Code = "N", Name = "N = None" },
				new FahCode() {FahFieldId =  "DischargedLoanCode", Code = "P", Name = "P = Permanent" },
				new FahCode() {FahFieldId =  "Fraud", Code = "TRUE", Name = "Y = Indicates fraud on one or more loans or overpayments" },
				new FahCode() {FahFieldId =  "GradCombinedLoanLimit", Code = "C", Name = "C = Close to or equal to loan limit" },
				new FahCode() {FahFieldId =  "GradCombinedLoanLimit", Code = "E", Name = "E = Exceed loan limit" },
				new FahCode() {FahFieldId =  "GradCombinedLoanLimit", Code = "R", Name = "R = Exceed loan limit and reaffirmed debt" },
				new FahCode() {FahFieldId =  "GradSubLoanLimit", Code = "C", Name = "C = Close to or equal to loan limit" },
				new FahCode() {FahFieldId =  "GradSubLoanLimit", Code = "E", Name = "E = Exceed loan limit" },
				new FahCode() {FahFieldId =  "GradSubLoanLimit", Code = "R", Name = "R = Exceed loan limit and reaffirmed debt" },
				new FahCode() {FahFieldId =  "GrantType", Code = "AG", Name = "ACG" },
				new FahCode() {FahFieldId =  "GrantType", Code = "SG", Name = "SMART" },
				new FahCode() {FahFieldId =  "GrantType", Code = "TG", Name = "TEACH" },
				new FahCode() {FahFieldId =  "LoanStatusCode", Code = "FR", Name = "FR = Fraud" },
				new FahCode() {FahFieldId =  "LoanStatusCode", Code = "IA", Name = "IA = Loan Originated" },
				new FahCode() {FahFieldId =  "LoanStatusCode", Code = "VA", Name = "Y = Indicates one or more discharged loans" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "CL", Name = "CL - FFELP Consolidation" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "D0", Name = "D0 - Direct Stafford Subsidized (SULA eligible)" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "D1", Name = "D1 - Direct Stafford Subsidized" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "D2", Name = "D2 - Direct Stafford Unsubsidized" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "D3", Name = "D3 - Direct Graduate PLUS" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "D4", Name = "D4 - Direct Parent PLUS" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "D5", Name = "D5 - Direct Consolidation Unsubsidized" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "D6", Name = "D6 - Direct Consolidation Subsidized" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "D7", Name = "D7 - Direct PLUS Consolidation" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "D8", Name = "D8 - Direct Unsubsidized TEACH Loan (converted from TEACH Grant)" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "D9", Name = "D9 - Direct Consolidation Subsidized (SULA Eligible)" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "GB", Name = "GB - FFELP Graduate PLUS" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "PL", Name = "PL - FFELP Parent PLUS" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "RF", Name = "RF - FFELP Refinanced" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "SF", Name = "SF - FFELP Stafford Subsidized" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "SL", Name = "SL - Supplemental Loan" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "SU", Name = "SU - FFELP Stafford Unsubsidized" },
				new FahCode() {FahFieldId =  "Overpayment", Code = "F", Name = "F = Indicates fraud designated through an overpayment" },
				new FahCode() {FahFieldId =  "Overpayment", Code = "Y", Name = "Y = Yes, an active overpayment exists" },
				new FahCode() {FahFieldId =  "OverpaymentType", Code = "AG", Name = "AG = Academic Competitive Grant (ACG)" },
				new FahCode() {FahFieldId =  "OverpaymentType", Code = "IA", Name = "IA = Iraq/Afghanistan Service Grant" },
				new FahCode() {FahFieldId =  "OverpaymentType", Code = "PE", Name = "PE = Pell Grant" },
				new FahCode() {FahFieldId =  "OverpaymentType", Code = "PK", Name = "PK = Perkins Loan (loan types DU, EU, NU, or PU)" },
				new FahCode() {FahFieldId =  "OverpaymentType", Code = "SE", Name = "SE = Federal Supplemental Educational Opportunity Grant" },
				new FahCode() {FahFieldId =  "OverpaymentType", Code = "SG", Name = "SG = National Science and Mathematics Access to Retain Talent (SMART) Grant" },
				new FahCode() {FahFieldId =  "OverpaymentType", Code = "TG", Name = "TG = Teacher Education Assistance for College and Higher Education (TEACH) Grant" },
				new FahCode() {FahFieldId =  "PellLifeLimit", Code = "C", Name = "C = Close to limit" },
				new FahCode() {FahFieldId =  "PellLifeLimit", Code = "E", Name = "E = Limit met or exceeded" },
				new FahCode() {FahFieldId =  "PellLifeLimit", Code = "H", Name = "H = High % warning" },
				new FahCode() {FahFieldId =  "PellLifeLimit", Code = "N", Name = "N = No problem" },
				new FahCode() {FahFieldId =  "Reaffirmation", Code = "TRUE", Name = "Y = Indicates one or more loans with active reaffirmation" },
				new FahCode() {FahFieldId =  "SulaFlag", Code = "TRUE", Name = "Y = The borrower is subject to the 150% Direct Subsidized Loan Limit provision" },
				new FahCode() {FahFieldId =  "TeachGrantConverted", Code = "TRUE", Name = "Y = Indicates a TEACH grant was converted to a TEACH loan on one or more grants" },
				new FahCode() {FahFieldId =  "UnderGradCombinedLoanLimit", Code = "C", Name = "C = Close to or equal to loan limit" },
				new FahCode() {FahFieldId =  "UnderGradCombinedLoanLimit", Code = "E", Name = "E = Exceed loan limit" },
				new FahCode() {FahFieldId =  "UnderGradCombinedLoanLimit", Code = "R", Name = "R = Exceed loan limit and reaffirmed debt" },
				new FahCode() {FahFieldId =  "UnderGradSubLoanLimit", Code = "C", Name = "C = Close to or equal to loan limit" },
				new FahCode() {FahFieldId =  "UnderGradSubLoanLimit", Code = "E", Name = "E = Exceed loan limit" },
				new FahCode() {FahFieldId =  "UnderGradSubLoanLimit", Code = "R", Name = "R = Exceed loan limit and reaffirmed debt" },
				new FahCode() {FahFieldId =  "UnusualEnrollHistory", Code = "2", Name = "2 = Possible enrollment history problem" },
				new FahCode() {FahFieldId =  "UnusualEnrollHistory", Code = "3", Name = "3 = Questionable enrollment history" },
				new FahCode() {FahFieldId =  "UnusualEnrollHistory", Code = "N", Name = "N = No problem" },
				new FahCode() {FahFieldId =  "UnusualEnrollment", Code = "2", Name = "Unusual Enrollment history requires review by the institution of the student’s enrollment records" },
				new FahCode() {FahFieldId =  "UnusualEnrollment", Code = "3", Name = "Institution must review academic records for the student and, in some instances, must collect additional documentation from the student" },
				new FahCode() {FahFieldId =  "HSProgramCode", Code = "Indicates the high school program code for ACG.  ", Name = "High School Program Code" },
				new FahCode() {FahFieldId =  "LastDisbAmount", Code = "Amount of last disbursement", Name = "Last Disbursement Amount" },
				new FahCode() {FahFieldId =  "LastDisbDate", Code = "Date school made the latest disbursement.", Name = "Latest Disbursement Date" },
				new FahCode() {FahFieldId =  "LastLoanDisbDate", Code = "Date latest loan disbursement was made.", Name = "Last Disbursement Date" },
				new FahCode() {FahFieldId =  "LastName", Code = "Last name of student submitted. ", Name = "Last Name" },
				new FahCode() {FahFieldId =  "LastNameHistory", Code = "Other last name used by the student for whom the FAH or Alert is provided. ", Name = "Last Name History" },
				new FahCode() {FahFieldId =  "LenderCode", Code = "Current Lender code or N/A if not applicable.", Name = "Lender Code" },
				new FahCode() {FahFieldId =  "LenderServicer", Code = "Current Lender Servicer code or N/A if not applicable.", Name = "Lender Servicer Code" },
				new FahCode() {FahFieldId =  "LifeEligibilityUsed", Code = "The Lifetime Eligibility Used (LEU) for Pell grants expressed as a decimal  ", Name = "Lifetime Eligibility Used (LEU)" },
				new FahCode() {FahFieldId =  "LoanAmount", Code = "Guaranteed/approved loan amount.", Name = "Loan Amount" },
				new FahCode() {FahFieldId =  "LoanChange", Code = "Indicates changed information on one or more loans. ", Name = "Loan Change Flag" },
				new FahCode() {FahFieldId =  "LoanContact", Code = "Code indicating the agency to be contacted for this loan.", Name = "Contact" },
				new FahCode() {FahFieldId =  "LoanDate", Code = "Date of loan guarantee/approval. ", Name = "Loan Date " },
				new FahCode() {FahFieldId =  "LoanPeriodBeginDate", Code = "Date the enrollment period begins for this loan.", Name = "Loan Period Begin Date" },
				new FahCode() {FahFieldId =  "LoanPeriodEndDate", Code = "Date the enrollment period ends for this loan.", Name = "Loan Period End Date" },
				new FahCode() {FahFieldId =  "LoanRecChange", Code = "Indicates change to this loan record. There will be a space for FAH records.", Name = "Loan Change Flag" },
				new FahCode() {FahFieldId =  "LoanSchoolCode", Code = "An 8-digit OPEID code used to identify the school attended by the student when the loan was originated. Last 2 digits equal 00 if no branch code. ", Name = "School Code" },
				new FahCode() {FahFieldId =  "LoanStatusCode", Code = "Code used to identify the current status of a student’s loan.", Name = "Current Loan Status Code" },
				new FahCode() {FahFieldId =  "LoanStatusDate", Code = "Date the current loan status code became effective. Format is CCYYMMDD.", Name = "Current Loan Status Date" },
				new FahCode() {FahFieldId =  "LoanTypeCode", Code = "Code indicating the type of loan.", Name = "Loan Type Code" },
				new FahCode() {FahFieldId =  "MiddleInitialHistory", Code = "Other middle initial used by the student for whom the FAH or Alert is provided, if available.", Name = "Middle Initial History" },
				new FahCode() {FahFieldId =  "NetLoanAmount", Code = "Amount of loan/guaranty minus total amount of cancellations and refunds.", Name = "Net Loan Amount" },
				new FahCode() {FahFieldId =  "OverDisbAY", Code = "Award Year on which the overpayment was disbursed.", Name = "Award Year" },
				new FahCode() {FahFieldId =  "Overpayment", Code = "One-character code that identifies the status of the overpayment.", Name = "Overpayment Indicator" },
				new FahCode() {FahFieldId =  "OverpaymentType", Code = "A 2-character code that identifies the type of overpayment(s) reported for the student.", Name = "Overpayment Type" },
				new FahCode() {FahFieldId =  "PellChange", Code = "Indicates change to Pell grant information on one or more grants. ", Name = "Pell Change Flag" },
				new FahCode() {FahFieldId =  "PellLifeLimit", Code = "Indicates the limit reached for the Pell Grant Lifetime Eligibility Used.", Name = "LEU Limit Indicator" },
				new FahCode() {FahFieldId =  "PerkinsCancelCode", Code = "Loan cancellation reasons. ", Name = "Perkins Cancellation Type Code" },
				new FahCode() {FahFieldId =  "PerkinsCurrentAYDisb", Code = "Total Perkins loan (DU, EU, NU, PU, and IC) disbursements for award year (July-June). ", Name = "Perkins Current Award Year Disbursement" },
				new FahCode() {FahFieldId =  "PerkinsTotalPrincipalBal", Code = "Total Perkins loan (DU, EU, NU, PU, and IC) outstanding principal balances. ", Name = "Perkins Total Outstanding Principal Balance" },
				new FahCode() {FahFieldId =  "PlusLoanPrincipalBal", Code = "Outstanding principal balance for PLUS loan types (PL, D4, and D7). Will be populated when the borrower is the PLUS loan holder", Name = "Aggregate PLUS Loans Outstanding Principal Balance" },
				new FahCode() {FahFieldId =  "PlusLoanTotal", Code = "Total for PLUS loan types (PL, D4, and D7). Will be populated when the borrower is the PLUS loan holder.", Name = "Aggregate PLUS Loans Total" },
				new FahCode() {FahFieldId =  "PlusProPrincipalBal", Code = "Outstanding principal balance for PLUS Graduate/Prof. loan types (D3 and GB).", Name = "Aggregate PLUS Graduate/Professional Outstanding Principal Balance" },
				new FahCode() {FahFieldId =  "PlusProTotal", Code = "Total for PLUS Graduate/Prof. loan types (D3 and GB).", Name = "Aggregate PLUS Graduate/Professional Total" },
				new FahCode() {FahFieldId =  "Post911DeceasedDep", Code = "Indicator for a Post 9/11 Deceased Veteran Dependent.", Name = "Post 911 Deceased Veteran Dependent Indicator" },
				new FahCode() {FahFieldId =  "PrincipalBal", Code = "Amount of outstanding principal balance. ", Name = "Outstanding Principal Balance" },
				new FahCode() {FahFieldId =  "PrincipalDate", Code = "Date the outstanding principal balance was last updated. Format is CCYYMMDD.", Name = "Outstanding Principal Balance Date" },
				new FahCode() {FahFieldId =  "Reaffirmation", Code = "Indicates if the loan has an active reaffirmation.", Name = "Reaffirmation flag" },
				new FahCode() {FahFieldId =  "ReceivedOn", Code = "Date Received", Name = "Date Received" },
				new FahCode() {FahFieldId =  "SatisfactoryRepayLoan", Code = "Indicates one or more loans with satisfactory repayment arrangements. ", Name = "Loan Satisfactory Repayment Arrangements Flag" },
				new FahCode() {FahFieldId =  "SchedAmount", Code = "Scheduled amount of the Federal Pell grant. TEACH grant scheduled award is $4,000.", Name = "Scheduled Amount" },
				new FahCode() {FahFieldId =  "SMARTChange", Code = "Indicates change to SMART grant information on one or more grants.", Name = "SMART Change Flag" },
				new FahCode() {FahFieldId =  "StartDate", Code = "Start Date", Name = "Start Date" },
				new FahCode() {FahFieldId =  "SubPendingDisb", Code = "Pending disbursements for subsidized loan types (D0, D1 and subsidized SF). ", Name = "Aggregate Subsidized Pending Disbursement (Undergraduate and Graduate)" },
				new FahCode() {FahFieldId =  "SubPrincipalBal", Code = "Outstanding principal balance for subsidized loan types (D0, D1, D6, and subsidized SF). Includes calculated share of a consolidation loan that is considered subsidized. ", Name = "Aggregate Subsidized Outstanding Principal Balance (Undergraduate and Graduate)" },
				new FahCode() {FahFieldId =  "SubTotal", Code = "Total of Aggregate Subsidized Outstanding Principal Balance and Aggregate Subsidized Pending Disbursement. ", Name = "Aggregate Subsidized Total (Undergraduate and Graduate)" },
				new FahCode() {FahFieldId =  "SubUsagePeriod", Code = "Indicates the total time during which the student has received Direct Subsidized Loans as reported to NSLDS by COD. This field contains numeric six-digit values, 000v000 to 999v999, where “v” is an implied decimal and is excluded from the output.", Name = "Subsidized Usage Period " },
				new FahCode() {FahFieldId =  "SulaFlag", Code = "Subsidized Usage Limit Applies (SULA) indicator on loan.", Name = "SULA Flag" },
				new FahCode() {FahFieldId =  "TEACHConversionDate", Code = "Date the TEACH grant was converted to a loan.", Name = "TEACH grant conversion date" },
				new FahCode() {FahFieldId =  "TEACHConverted", Code = "Indicates TEACH grant was converted to a loan. ", Name = "TEACH grant converted to loan flag" },
				new FahCode() {FahFieldId =  "TeachGrantChange", Code = "Indicates changed TEACH grant Aggregate Amount information. ", Name = "TEACH Grant Aggregates Change Flag" },
				new FahCode() {FahFieldId =  "TeachGrantConverted", Code = "Indicates a TEACH grant was converted to a TEACH loan on one or more grants.", Name = "TEACH Grant Converted to Loan Flag" },
				new FahCode() {FahFieldId =  "TeachGrantDataChange", Code = "Indicates change to TEACH grant information on one or more grants.", Name = "TEACH Grant Data Change Flag" },
				new FahCode() {FahFieldId =  "TeachLoanChange", Code = "Indicates changed TEACH loan Aggregate Amount information. ", Name = "TEACH Loan Aggregate Change Flag" },
				new FahCode() {FahFieldId =  "TeachLoanPrincipalBal", Code = "Outstanding principal balance for TEACH unsubsidized loan type (D8).  ", Name = "TEACH Loan OPB" },
				new FahCode() {FahFieldId =  "TeachLoanTotal", Code = "Total of Aggregate TEACH Unsubsidized loan Outstanding Principal Balance. ", Name = "TEACH Loan Total" },
				new FahCode() {FahFieldId =  "TotalDisb", Code = "Cumulative amount disbursed. ", Name = "Total Disbursement Amount" },
				new FahCode() {FahFieldId =  "TotalEligibilityUsed", Code = "The total percent of eligibility used for ACG and SMART grants.  ", Name = "Total Percent Eligibility Used by Academic Year Level" },
				new FahCode() {FahFieldId =  "TransNumber", Code = "Transaction number on the SAR or ISIR for the payment accepted by the school.", Name = "Transaction Number" },
				new FahCode() {FahFieldId =  "UnallocatedAmount", Code = "Amount that could not be determined to be subsidized, unsubsidized or Perkins.", Name = "Consolidation Unallocated Aggregate OPB" },
				new FahCode() {FahFieldId =  "UnAllocPrincipalBal", Code = "Aggregate Outstanding principal balance for Consolidation Loans, Unallocated.", Name = "Aggregate Consolidation Loans, Unallocated Outstanding Principal Balance (Undergraduate and Graduate)" },
				new FahCode() {FahFieldId =  "UnAllocPrincipalTotal", Code = "Aggregate Total for Consolidation Loans, Unallocated.", Name = "Aggregate Consolidation Loans, Unallocated Total (Undergraduate and Graduate)" },
				new FahCode() {FahFieldId =  "UndergradAY", Code = "Award year used in the student’s undergraduate loan limits determination.", Name = "Undergraduate Award Year" },
				new FahCode() {FahFieldId =  "UnderGradCombinedLoanLimit", Code = "Flag indicating the condition of the Aggregate Total` combined loan limit at the undergraduate level.", Name = "Undergraduate Combined Loan Limit Flag" },
				new FahCode() {FahFieldId =  "UndergradCombinedPendingDisb", Code = "Pending disbursements for undergraduate subsidized and unsubsidized loan types (D0, D1, D2, SF, and SU).", Name = "Undergraduate Aggregate Combined Pending Disbursement " },
				new FahCode() {FahFieldId =  "UndergradCombinedPrincipalBal", Code = "Outstanding principal balance for undergraduate subsidized and unsubsidized loan types (D0, D1, D2, D5, D6, FI, RF, subsidized and non-subsidized SF, SL, and SU). Includes the total amount of an undergraduate consolidation loan, excluding the calculated s", Name = "Undergraduate Aggregate Combined Outstanding Principal Balance" },
				new FahCode() {FahFieldId =  "UndergradCombinedTotal", Code = "Total of Undergraduate Aggregate Combined Outstanding Principal Balance and Undergraduate Aggregate Combined Pending Disbursements. ", Name = "Undergraduate Aggregate Combined Total " },
				new FahCode() {FahFieldId =  "UndergradDependency", Code = "Indicator of the dependency used in the student’s undergraduate loan limits determination.", Name = "Undergraduate Dependency Indicator" },
				new FahCode() {FahFieldId =  "UndergradEligibilityUsed", Code = "TEACH grant’s awarded percent used by Undergraduate/Post Baccalaureate Academic Levels.", Name = "Undergraduate % Eligibility Used" },
				new FahCode() {FahFieldId =  "UndergradRemainingAmount", Code = "The remaining eligible amount by Undergraduate/Post Baccalaureate Academic Levels.", Name = "Undergraduate Remaining Amount" },
				new FahCode() {FahFieldId =  "UnderGradSubLoanLimit", Code = "Flag indicating the condition of the Aggregate Total for subsidized loan limit (Loan types include: DO, D1, D6, subsidized SF, and calculated share of consolidation loan considered to be subsidized.) at the undergraduate level.", Name = "Undergraduate Subsidized Loan Limit Flag" },
				new FahCode() {FahFieldId =  "UndergradSubPendingDisb", Code = "Pending disbursements for undergraduate subsidized loan types (D0, D1 and subsidized SF). ", Name = "Undergraduate Aggregate Subsidized Pending Disbursement " },
				new FahCode() {FahFieldId =  "UndergradSubPrincipalBal", Code = "Outstanding principal balance for undergraduate subsidized loan types (D0, D1, D6, and subsidized SF). Includes calculated share of an undergraduate consolidation loan that is considered subsidized. ", Name = "Undergraduate Aggregate Subsidized Outstanding Principal Balance" },
				new FahCode() {FahFieldId =  "UndergradSubTotal", Code = "Total of Undergraduate Aggregate Subsidized Outstanding Principal Balance and Undergraduate Aggregate Subsidized Pending Disbursements. ", Name = "Undergraduate Aggregate Subsidized Total " },
				new FahCode() {FahFieldId =  "UndergradTeachDisbTotal", Code = "Aggregate Undergraduate/Post Baccalaureate TEACH grant disbursed amounts for the following Academic Levels:", Name = "Aggregate Total TEACH Grant Undergraduate Disbursement Amount" },
				new FahCode() {FahFieldId =  "UndergradUnallocPrincipalBal", Code = "Outstanding principal balance for undergraduate consolidation loan amount determined to be unallocated.", Name = "Undergraduate Aggregate Consolidation Loans, Unallocated Outstanding Principal Balance" },
				new FahCode() {FahFieldId =  "UndergradUnallocTotal", Code = "Undergraduate Aggregate Total for consolidation loan amount determined to be unallocated. ", Name = "Undergraduate Aggregate Consolidation Loans, Unallocated Total " },
				new FahCode() {FahFieldId =  "UndergradUnsubPendingDisb", Code = "Pending disbursements for undergraduate unsubsidized loan types (D2 and SU). ", Name = "Undergraduate Aggregate Unsubsidized Pending Disbursement " },
				new FahCode() {FahFieldId =  "UndergradUnsubPrincipalBal", Code = "Outstanding principal balance for undergraduate unsubsidized loan types (D2, D5, FI, RF, non-subsidized SF, SL, and SU). Includes calculated share of an undergraduate consolidation loan that is considered unsubsidized. ", Name = "Undergraduate Aggregate Unsubsidized Outstanding Principal Balance" },
				new FahCode() {FahFieldId =  "UndergradUnsubTotal", Code = "Total of Undergraduate Aggregate Unsubsidized Outstanding Principal Balance and Undergraduate Aggregate Unsubsidized Pending Disbursements. ", Name = "Undergraduate Aggregate Unsubsidized Total " },
				new FahCode() {FahFieldId =  "UnSubPendingDisb", Code = "Pending disbursements for unsubsidized loan types (D2 and SU). ", Name = "Aggregate Unsubsidized Pending Disbursement (Undergraduate and Graduate)" },
				new FahCode() {FahFieldId =  "UnSubPrincipalBal", Code = "Outstanding principal balance for unsubsidized loan types (D2, D5, FI, RF, non-subsidized SF, SL, and SU) Includes calculated share of a consolidation loan that is considered unsubsidized. ", Name = "Aggregate Unsubsidized Outstanding Principal Balance (Undergraduate and Graduate)" },
				new FahCode() {FahFieldId =  "UnSubTotal", Code = "Total of Aggregate Unsubsidized Outstanding Principal Balance and Aggregate Unsubsidized Pending Disbursement. ", Name = "Aggregate Unsubsidized Total (Undergraduate and Graduate)" },
				new FahCode() {FahFieldId =  "UnusualEnrollHistory", Code = "Indicates a student’s Pell Grant and loan awarding activity pattern that looks suspicious.", Name = "Unusual Enrollment History Indicator" },
				new FahCode() {FahFieldId =  "ValidUntil", Code = "History Valid Until", Name = "History Valid Until" },

			};
			return fc.AsQueryable();
		}


		public static IQueryable<PellAward> GetTestPellAwards()
		{
			List<PellAward> pa = new List<PellAward>()
			{
				new PellAward() {AwardYear =  2017, AYDisplay = "16/17", MaxAmount = 5815, AdditionalPercent = 0 },
				new PellAward() {AwardYear =  2018, AYDisplay = "17/18", MaxAmount = 5920, AdditionalPercent = 50 },
				new PellAward() {AwardYear =  2019, AYDisplay = "18/19", MaxAmount = 5920, AdditionalPercent = 50 }
			};
			return pa.AsQueryable();
		}
		public static ClientProfile GetTestClientProfile()
		{
			return new ClientProfile()
			{
				Id = 1,
				Address1 = "105  26th Ave. S.W.",
				Address2 = "Suite 101",
				AY_Definition = 1,
				City = "Calgary",
				Contact = "BRS_BRS",
				Email = "b@tntzone.com",
				Exits_Counseling = false,
				Expiration = 365,
				IsDeleted = false,
				Monitoring = 0,
				OPEID = "ITTENANT",
				Organization_Name = "Work@Home",
				Phone = "arag",
				SAIG = "1234356",
				State = "ON",
				Zip = "l1j4g6",
				TD_Password = null,
				IsPwdValid = true,
				Upload_Method = "",
				LastPwdChanged = null
			};
		}
	}
}
